version: "3"
services:
  ics-os-build:
    build: .
    command:
      - /bin/bash
    volumes:
      - .:/home/ics-os
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
